name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    name: Lint, Test, and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[development]

      - name: Run Ruff (Linter)
        run: |
          ruff check .
          ruff format --check .

      - name: Run MyPy (Static Type Checker)
        run: mypy .

      - name: Run Tests with Coverage
        run: |
          pytest --cov=data_science_stuff --cov-report=xml
          coverage report -m

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
